version: "2"
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 200
  nested-control-flow:
    config:
      threshold: 8
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: 200
exclude_patterns:
  - "**/__tests__/"
